name: release

on: push

jobs:
  upload-plugin-code:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive

    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: "5.1.5"

    - uses: leafo/gh-actions-luarocks@v2

    - name: build
      run: |
        luarocks make --pack-binary-rock

    - name: unzip and repack
      run: |
        mkdir output
        mv kong-oidc-1.6.0-1.all.rock output
        cd output
        unzip kong-oidc-1.6.0-1.all.rock
        cd ..
        mkdir kong-oidc-1.6.0
        cp LICENSE kong-oidc-1.6.0/
        cp output/lua/kong/plugins/oidc/*.lua kong-oidc-1.6.0/
        zip -r kong-oidc-1.6.0.zip kong-oidc-1.6.0
    
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: plugin-code
        path: kong-oidc-1.6.0.zip
